### ISSUE TITLE
Crash on Fabric 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#40]
### Bug description

[main/ERROR]: Mixin apply for mod carpet-ams-addition failed amscarpet.mixins.json:rule.opPlayerNoCheatExtra.DataCommandMixin from mod carpet-ams-addition -> net.minecraft.class_3164: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on executeInsert could not find any targets matching 'executeInsert' in net.minecraft.class_3164. Using refmap Carpet-AMS-Addition-mc1.20.2-refmap.json [PREINJECT Applicator Phase -> amscarpet.mixins.json:rule.opPlayerNoCheatExtra.DataCommandMixin from mod carpet-ams-addition -> Prepare Injections ->  -> handler$ban000$carpet-ams-addition$executeInsert(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on executeInsert could not find any targets matching 'executeInsert' in net.minecraft.class_3164. Using refmap Carpet-AMS-Addition-mc1.20.2-refmap.json [PREINJECT Applicator Phase -> amscarpet.mixins.json:rule.opPlayerNoCheatExtra.DataCommandMixin from mod carpet-ams-addition -> Prepare Injections ->  -> handler$ban000$carpet-ams-addition$executeInsert(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor20.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3050.method_13298(class_3050.java:585) ~[server-intermediary.jar:?]
	at net.minecraft.class_3050.method_13271(class_3050.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:171) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:945) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.2]
[15:59:17] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3164 failed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:206) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.2]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3164 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3050.method_13298(class_3050.java:585) ~[server-intermediary.jar:?]
	at net.minecraft.class_3050.method_13271(class_3050.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:171) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:945) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-intermediary.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3050.method_13298(class_3050.java:585) ~[server-intermediary.jar:?]
	at net.minecraft.class_3050.method_13271(class_3050.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:171) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:945) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-intermediary.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [amscarpet.mixins.json:rule.opPlayerNoCheatExtra.DataCommandMixin from mod carpet-ams-addition] from phase [DEFAULT] in config [amscarpet.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3050.method_13298(class_3050.java:585) ~[server-intermediary.jar:?]
	at net.minecraft.class_3050.method_13271(class_3050.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:171) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:945) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-intermediary.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on executeInsert could not find any targets matching 'executeInsert' in net.minecraft.class_3164. Using refmap Carpet-AMS-Addition-mc1.20.2-refmap.json [PREINJECT Applicator Phase -> amscarpet.mixins.json:rule.opPlayerNoCheatExtra.DataCommandMixin from mod carpet-ams-addition -> Prepare Injections ->  -> handler$ban000$carpet-ams-addition$executeInsert(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor20.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_3050.method_13298(class_3050.java:585) ~[server-intermediary.jar:?]
	at net.minecraft.class_3050.method_13271(class_3050.java:163) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.<init>(class_2170.java:171) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:50) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.method_43612(Main.java:159) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:945) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:939) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-intermediary.jar:?]
	... 5 more

### Steps to reproduce

/

### Minecraft version

1.20.2

### TemplateMod version

Carpet-AMS-Addition-mc1.20.2-v2.10.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 1024-byteeeee** [comment]
😵还是有问题，我待会儿瞅瞅把，1.19的data指令有改动，你的客户端会崩溃吗？

**Comment by sternschnaube** [comment]
Client loads fine 😊
Thanks for the fast answer.

**Comment by 1024-byteeeee** [comment]
我要如何重现这个错误？我无论是客户端还是服务端都没有这个情况。
How can I reproduce this error? I am not encountering this situation on either the client or server.
Sorry my English is poor, this is translated by CHAT-GPT lol.

**Comment by sternschnaube** [comment]
I have a large list of mods, but let's look first into other carpet extensions.

carpet-addons-not-found-1.20.2-1.3.1.jar
carpet-autocraftingtable-1.20.2-1.4.113.jar
carpet-extra-1.20.2-1.4.118.jar
carpet-tis-addition-mc1.20.2-v1.53.1.jar
CarpetTCTCAddition-1.20.2-2.2.208+0fb0eb0-stable.jar

**Comment by sternschnaube** [comment]
I was looking into the issue and I found it.
I removed the folder "AmsData" from the "datapacks" directory.
Now after moving it back into it, the mod loads fine on the server-side.

This can be closed but maybe it's helpfully and you can include a check for this or something.

**Comment by 1024-byteeeee** [comment]
> 我正在调查这个问题，我找到了它。我从“datapacks”目录中删除了文件夹“AmsData”。现在，在将其移回其中后，mod 在服务器端加载良好。
> 
> 这可以关闭，但也许它会有所帮助，您可以为此或其他东西进行检查。

Thank you very much.
